// const appError = require('../utils/appError');
const catchAsync = require('../utils/catchAsync');

exports.getbug = catchAsync(async (req, res, next) => {});
